### ISSUE TITLE
stacktrace starting

### ISSUE THREAD

**Issue by SvenDowideit** [workbenchapp/solana-workbench#24]
```
[290680:0228/144856.485627:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
14:48:56.609 › APPIMAGE env is not defined, current application is not an AppImage
<i> [webpack-dev-middleware] wait until bundle finished: /index.html
2022-02-28T04:49:25.170Z INFO IPC event                                         method=subscribe-program-changes net=localhost programID=11111111111111111111111111111111
2022-02-28T04:49:25.182Z INFO OK                                                method=subscribe-program-changes
2022-02-28T04:49:25.184Z INFO IPC event                                         method=accounts net=localhost
2022-02-28T04:49:25.185Z INFO IPC event                                         method=validator-state net=localhost
2022-02-28T04:49:25.224Z INFO OK                                                method=validator-state running=true
2022-02-28T04:49:25.353Z INFO accounts                                          net=localhost pubKey=DpG8CP3azZj1LZsCwbzscnNquGc9HgZVSXkJXC9u21rM
2022-02-28T04:49:25.374Z INFO existingAccounts                                  existingAccounts=""
2022-02-28T04:49:25.390Z INFO adding account                                    acc_pubkey=EUUUDo8mfULhqSwjJZFUKGPYctPYWo8pbRtgtg97nkXv
2022-02-28T04:49:25.408Z INFO adding account                                    acc_pubkey=DyX2vdjQgjbomU4BZ23RxHw8UAktG64PD8Rgduw8Drhd
2022-02-28T04:49:25.424Z INFO adding account                                    acc_pubkey=GPWCT2rfNZ3z7SDqrM9oQdCVMhpbth4TS44p4e55hNkd
2022-02-28T04:49:25.444Z INFO adding account                                    acc_pubkey=8B7rAkqwoZm5vUpBRx8cpxbJgEceHYYZV2ZBSYb498eb
2022-02-28T04:49:25.457Z INFO adding account                                    acc_pubkey=BfGj1A2dxSHM7HrR3nPBgnAiFwn6sbvUSqg69oTmPMYS
Transaction simulation failed: Attempt to debit an account but found no record of a prior credit. 
    
2022-02-28T04:49:26.046Z ERROR ERROR                                             method=accounts name=Error
2022-02-28T04:49:26.047Z ERROR Stacktrace:                                       
2022-02-28T04:49:26.048Z ERROR  Error: failed to send transaction: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
2022-02-28T04:49:26.048Z ERROR      at Connection.sendEncodedTransaction (/home/sven/src/cryptoworkbench/solana-workbench/release/app/node_modules/@solana/web3.js/src/connection.ts:3689:13)
2022-02-28T04:49:26.048Z ERROR      at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-02-28T04:49:26.048Z ERROR      at async Connection.sendRawTransaction (/home/sven/src/cryptoworkbench/solana-workbench/release/app/node_modules/@solana/web3.js/src/connection.ts:3649:20)
2022-02-28T04:49:26.049Z ERROR      at async Connection.sendTransaction (/home/sven/src/cryptoworkbench/solana-workbench/release/app/node_modules/@solana/web3.js/src/connection.ts:3637:12)
2022-02-28T04:49:26.049Z ERROR      at async Object.sendAndConfirmTransaction (/home/sven/src/cryptoworkbench/solana-workbench/release/app/node_modules/@solana/web3.js/src/util/send-and-confirm-transaction.ts:29:21)
2022-02-28T04:49:26.050Z ERROR      at async accounts (/home/sven/src/cryptoworkbench/solana-workbench/src/main/accounts.ts:156:19)
2022-02-28T04:49:26.050Z ERROR      at async IpcMainImpl.<anonymous> (/home/sven/src/cryptoworkbench/solana-workbench/src/main/main.ts:51:17)
```

**Comment by SvenDowideit** [comment]
We don't do things this way atm
